/**
 * Official site for each stack/tool name mentioned across the site
 * (works detail meta, about section skills). Names without an entry
 * render as plain text — used for generic skills that don't have one
 * canonical vendor page (e.g. "Wireframing", "SQL").
 */
export const STACK_LINKS: Record<string, string> = {
  "Next.js": "https://nextjs.org",
  GSAP: "https://gsap.com",
  Nuqs: "https://nuqs.dev",
  Zod: "https://zod.dev",
  "shadcn/ui": "https://ui.shadcn.com",
  Prisma: "https://www.prisma.io",
  tRPC: "https://trpc.io",
  "Sanity CMS": "https://www.sanity.io",
  Sanity: "https://www.sanity.io",
  Mantine: "https://mantine.dev",
  "TanStack Query": "https://tanstack.com/query",
  "Payload CMS": "https://payloadcms.com",
  Payload: "https://payloadcms.com",
  "Framer Motion": "https://motion.dev",
  "Motion (formerly Framer Motion)": "https://motion.dev",
  HTML: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  CSS: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  "CSS Modules": "https://github.com/css-modules/css-modules",
  TypeScript: "https://www.typescriptlang.org",
  JavaScript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  PHP: "https://www.php.net",
  jQuery: "https://jquery.com",
  Java: "https://www.java.com",
  C: "https://en.cppreference.com/w/c",
  "C++": "https://isocpp.org",
  "C#": "https://learn.microsoft.com/en-us/dotnet/csharp/",
  Dart: "https://dart.dev",
  React: "https://react.dev",
  Vue: "https://vuejs.org",
  Nuxt: "https://nuxt.com",
  Express: "https://expressjs.com",
  Laravel: "https://laravel.com",
  Flutter: "https://flutter.dev",
  Astro: "https://astro.build",
  Tailwind: "https://tailwindcss.com",
  PostgreSQL: "https://www.postgresql.org",
  MongoDB: "https://www.mongodb.com",
  Oracle: "https://www.oracle.com/database/",
  Firebase: "https://firebase.google.com",
  Supabase: "https://supabase.com",
  Figma: "https://www.figma.com",
  Cursor: "https://cursor.com",
  "Claude (Code, Cowork, Design)": "https://claude.com",
  Claude: "https://claude.com",
}
